server:
  port: 7001

spring:
  application:
    name: product-service-2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

