server:
  port: 7003

spring:
  application:
    name: order-service-2
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        default:zone: http://localhost:8761/eureka
      instance:
        hostname: localhost